### PR TITLE
fixed typos, grammar, and colon usages in README

### PR DESCRIPTION
**Pull request by nick-w-nick**
I noticed there were a few typos/grammatical issues in the README, thought I'd submit a quick PR to fix them.

Thanks!

### CODE REVIEW

**Review by ozziest — COMMENTED** [review]
Thank you very much for the quick PR. 👏 👏 

I can merge this PR now. But, there are some changes coming on the `develop` branch. We will have a minimalist [readme file](https://github.com/axe-api/axe-api/blob/develop/readme.md). 

I can suggest you fix the readme file on the `develop` branch instead of merging this. What do you think?  🤔

**Comment by nick-w-nick** [comment]
@ozziest The minimalist README on `develop` seems to exclude all of the text that was previously fixed.

Do you want me to add this information to the README on `develop`, or just close it in favor of the minimalist version?

**Comment by nick-w-nick** [comment]
No problem, thanks for the heads up!

I'll look over the docs repo and see if there are any fixes that could be made there.

**Comment by ozziest** [comment]
Thanks! That's great. 😊

**Pull request closed without merging**
